services:
  - type: web
    name: tronmap
    env: python
    region: oregon
    branch: flare-deploy
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DEBUG
        value: "False"
